# Generated by Django 4.1.2 on 2022-11-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stored_xss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='challenge_assigned',
            field=models.CharField(choices=[('1', 'level1'), ('2', 'level2')], max_length=1, null=True),
        ),
    ]
