# Generated by Django 4.1.2 on 2022-11-09 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '__first__'),
        ('stored_xss', '0002_comment_challenge_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('stored_xss_module_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.storedxssmodule')),
            ],
        ),
    ]
