# Generated by Django 4.1.2 on 2022-11-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stored_xss', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
